import Head from 'next/head';
import { BsFillMoonStarsFill } from "react-icons/bs"
import {
    AiFillFacebook,
    AiFillLinkedin,
    AiFillMail,
    AiFillGithub
} from "react-icons/ai";
import Image from "next/image";
import desgin from "../public/design.png";
import consulting from "../public/consulting.png";
import code from "../public/code.png";
import wine from "../public/wine.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.jpg";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import web7 from "../public/web7.png";
import web8 from "../public/web8.png";
import { useState } from "react";
export default function Home() {
   const [darkMode, setDarkMode] = useState(false);
 const [status, setStatus] = useState({
        submitted: false,
        submitting: false,
        info: { error: false, msg: null },
    });

    const [inputs, setInputs] = useState({
        email: '',
        message: '',
    });

    const handleResponse = (status, msg) => {
        if (status === 200) {
            setStatus({
                submitted: true,
                submitting: false,
                info: { error: false, msg: msg },
            });
            setInputs({
                email: '',
                message: '',
            });
        } else {
            setStatus({
                info: { error: true, msg: msg },
            });
        }
    };

    const handleOnChange = (e) => {
        e.persist();
        setInputs((prev) => ({
            ...prev,
            [e.target.id]: e.target.value,
        }));
        setStatus({
            submitted: false,
            submitting: false,
            info: { error: false, msg: null },
        });
    };

    const handleOnSubmit = async (e) => {
        e.preventDefault();
        setStatus((prevStatus) => ({ ...prevStatus, submitting: true }));
        const res = await fetch('/api/send', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(inputs),
        });
        const text = await res.text();
        handleResponse(res.status, text);
    };
  
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Personal Portfolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">YWine</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                 onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />  
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="../public/Wine Pyae Sone Maung.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-5 py-5">
            <h2 className="text-2xl py-1 text-teal-600 font-medium dark:text-teal-400 md:text-4xl">
             Wine Pyae Sone Maung
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let is get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillFacebook />
              <AiFillLinkedin />
              < AiFillMail />
              <AiFillGithub/>
            </div>
            <div className=" mx-auto bg-gradient-to-b from-teal-500 rounded-full w-40 h-80 relative overflow-hidden mt-10 md:h-96 md:w-96">
              <Image src={wine}  layout="fill" objectFit="cover"/>
            </div>
          </div>
        </section>  

        {/* Tools sections */}
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I have done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white   flex-1">
              <Image src={desgin} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">Java script</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
              <p className="text-gray-800 py-1">Other frame work</p>
              
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let is make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Development Tools I Use</h4>
              <p className="text-gray-800 py-1">PHP</p>
              <p className="text-gray-800 py-1">Laravel(framework)</p>
              <p className="text-gray-800 py-1">MySql database</p>
              <p className="text-gray-800 py-1">vue js (faramework)</p>
              <p className="text-gray-800 py-1">API</p>
              <p className="text-gray-800 py-1">Domain hosting</p>
              <p className="text-gray-800 py-1">Sever deployment</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Consulting </h4>
              <p className="text-gray-800 py-1">Creative thinking</p>
              <p className="text-gray-800 py-1">Thinking conceptually and practically</p>
              <p className="text-gray-800 py-1">Problem-solving</p>
              <p className="text-gray-800 py-1">Communicating clearly and empathetically</p>
              <p className="text-gray-800 py-1">Collaboration with all job levels</p>
              <p className="text-gray-800 py-1">Curiosity and Credibility</p>
            </div>
          </div>
        </section>
         <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I have done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          
        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover " width src={web1}
              />
            </div>
            <div className=" basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"src={web2}
              />
            </div>
             <div className=" basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"src={web5}
              />
            </div>
             <div className=" basis-1/3 flex-1 ">
              <Image
                className=""src={web4}
              />
            </div>
             <div className=" basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"src={web3}
              />
            </div>
             <div className=" basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"src={web6}
              />
            </div>
               <div className=" basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"src={web7}
              />
            </div>
               <div className=" basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"src={web8}
              />
            </div>
              
            
            

          </div>
          <form
                    onSubmit={handleOnSubmit}
                    className="relative w-full px-4 mx-auto max-w-lg"
                >
                    <h1 className="relative text-center font-light text-3xl leading-relaxed lg:text-5xl">
                        <span className="uppercase font-bold tracking-10 text-teal-500">
                            Contact me
                        </span>
                    </h1>

                    <div className="mt-10">
                        <label className='text-teal-500' htmlFor="email">Email</label>
                        <input
                            className="block w-full p-2 bg-gray-800 border border-white focus:outline-none"
                            id="email"
                            type="email"
                            onChange={handleOnChange}
                            required
                            placeholder="your@email.com"
                            value={inputs.email}
                        />
                    </div>
                    <div className="mt-10">
                        <label className='text-teal-500' htmlFor="message">Message</label>
                        <textarea
                            className="block w-full p-2 bg-gray-800 border border-white focus:outline-none"
                            id="message"
                            onChange={handleOnChange}
                            required
                            rows={10}
                            value={inputs.message}
                            placeholder="Your message..."
                        />
                    </div>
                    <button
                        className="mt-10 py-2 px-4 border-2 border-white text-white uppercase text-sm tracking-24 bg-transparent hover:bg-white hover:text-gray-900 transition duration-150 ease-in-out"
                        type="submit"
                        disabled={status.submitting}
                    >
                        {!status.submitting
                            ? !status.submitted
                                ? 'Submit'
                                : 'Submitted'
                            : 'Submitting...'}
                    </button>
                    <div className="mt-4">
                        {status.info.error && (
                            <div className="error">
                                Error: {status.info.msg}
                            </div>
                        )}
                        {!status.info.error && status.info.msg && (
                            <div className="success">{status.info.msg}</div>
                        )}
                    </div>
                </form>
        </section>
      </main>
    </div>
  );
}